services:
  postgres:
    image: postgres:alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
